module.exports = {
  challenge_ctrl: require('./controller/challenge_ctrl'),
  pointpassage_ctrl: require('./controller/pointpassage_ctrl'),
  segment_ctrl: require('./controller/segment_ctrl'),
  obstacle_ctrl: require('./controller/obstacle_ctrl'),
  event_ctrl: require('./controller/event_ctrl'),
  participation_ctrl: require('./controller/participation_ctrl'),
  imagesubmition_ctrl: require('./controller/imagesubmition_ctrl'),
  user_ctrl: require('./controller/user_ctrl'),
  google_ctrl: require('./controller/google_ctrl'),
  propositionchallenge_ctrl: require('./controller/propositionchallenge_ctrl'),
  challengetovote_ctrl: require('./controller/challengetovote_ctrl'),
  fraude_ctrl: require('./controller/fraude_ctrl'),
  utils: require('./utils'),
};
