version: "3"
services:
  web:
    build: .
    environment:
      - NODE_ENV=development
      - BDD_URL=mysql://acrobat:acrobat@database/database
      - DEBUG=serveur:*
      - JWT_SECRET=123456
      - HOST=http://localhost:1418
      - DOC_NAME=Acrobatt
      - DOC_HOST=http://localhost:1418
    ports:
      - 1418:1418
    command: npm run dev
    volumes:
      - ./:/app
  database:
    image: mysql:5.7
    ports:
      - 1419:3306
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=acrobat
      - MYSQL_PASSWORD=acrobat
      - MYSQL_ROOT_PASSWORD=acrobat